const router = require('express').Router();
const controller = require('../controllers/orderController');
const auth = require('../middleware/auth');
const admin = require('../middleware/admin');
router.post('/', auth.optional, controller.createOrder);
router.get('/mine', auth, controller.getUserOrders);
router.get('/', auth, admin, controller.getOrders);
router.patch('/:id', auth, admin, controller.updateOrder);
router.delete('/:id', auth, admin, controller.deleteOrder);
module.exports = router;
