// Works when opened through either Node (:3000) or VS Code Live Server (:5500).
const API = `${location.protocol}//${location.hostname || 'localhost'}:3000/api`;
const menu = [
  { name:'beef_olympus', label:'Olympus 經典牛肉堡', price:240 }, { name:'chicken_storm', label:'風暴香酥雞腿堡', price:165 },
  { name:'pork_bbq', label:'火星煙燻 BBQ 豬肉堡', price:185 }, { name:'beef_truffle', label:'Truffle 松露牛肉堡', price:210 },
  { name:'chicken_honey', label:'蜂蜜芥末雞肉堡', price:175 }, { name:'veggie_falafel', label:'香料鷹嘴豆蔬食堡', price:170 },
  { name:'chicken_pork', label:'韓式烤肉雞腿堡', price:180 }, { name:'beef_curiosity', label:'Curiosity 牛肉起司堡', price:160 },
  { name:'beef_peanut', label:'花生培根牛肉堡', price:195 }, { name:'veggie_oasis', label:'Oasis 綠洲蔬食堡', price:155 },
  { name:'combo_a', label:'A 號火星套餐', price:110 }, { name:'combo_b', label:'B 號太空套餐', price:95 },
  { name:'side_fries', label:'經典脆薯', price:55 }, { name:'side_tater_tots', label:'星球薯球', price:75 },
  { name:'side_fried_chicken', label:'火星炸雞', price:65 }, { name:'side_tenders', label:'香脆雞柳條', price:80 },
  { name:'drink_soda', label:'氣泡飲', price:40 }, { name:'drink_sprite', label:'檸檬汽水', price:40 },
  { name:'drink_tea', label:'冰茶', price:40 }, { name:'drink_coffee', label:'宇宙咖啡', price:79 },
  { name:'drink_sunset', label:'日落特調', price:99 }, { name:'combo_c', label:'C 號豪華套餐', price:149 }
];
let cart = [], salesChart;
const $ = s => document.querySelector(s);
const token = () => localStorage.getItem('mars_token');
const user = () => JSON.parse(localStorage.getItem('mars_user') || 'null');
const request = async (path, options = {}) => { const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(token() ? { Authorization: `Bearer ${token()}` } : {}), ...options.headers }, ...options }); const body = response.headers.get('content-type')?.includes('application/json') ? await response.json() : await response.text(); if (!response.ok) throw new Error(body.message || '操作失敗'); return body; };
const money = n => new Intl.NumberFormat('zh-TW', { style: 'currency', currency: 'TWD', maximumFractionDigits: 0 }).format(n);

function renderMenu() { $('#menu').innerHTML = menu.map((item, i) => `<div class="col-md-4 mb-3"><div class="card food-card h-100 overflow-hidden"><img src="images/${item.name}.jpg" alt="${item.label}" class="card-img-top" style="height:160px;object-fit:cover"><div class="card-body d-flex flex-column"><h5>${item.label}</h5><p class="price mt-auto">${money(item.price)}</p><button class="btn btn-outline-danger" onclick="addCart(${i})">加入購物車</button></div></div></div>`).join(''); }
function renderCart() { const count = cart.reduce((n, x) => n + x.quantity, 0); $('#cartCount').textContent = count; $('#cart').innerHTML = cart.length ? `${cart.map((x, i) => `<div>${x.label || x.name} × ${x.quantity}　${money(x.price * x.quantity)} <button class="btn btn-sm btn-link text-danger" onclick="removeCart(${i})">移除</button></div>`).join('')}<hr><strong>總計：${money(cart.reduce((n,x) => n+x.price*x.quantity,0))}</strong>` : '尚未加入商品'; }
window.addCart = i => { const found = cart.find(x => x.name === menu[i].name); found ? found.quantity++ : cart.push({ ...menu[i], quantity: 1 }); renderCart(); };
window.removeCart = i => { cart.splice(i, 1); renderCart(); };
function renderAccount() { const u = user(); $('#accountArea').innerHTML = u ? `<span class="text-white me-2">${u.username}${u.role === 'admin' ? '（管理員）' : ''}</span><button class="btn btn-sm btn-outline-light" onclick="logout()">登出</button>` : ''; $('#authPanel').style.display = u ? 'none' : ''; if (u?.role === 'admin' && $('#admin')) $('#admin').style.display = 'block'; }
window.logout = () => { localStorage.removeItem('mars_token'); localStorage.removeItem('mars_user'); location.reload(); };
async function loadMine() { if (!token()) return; try { const { orders } = await request('/orders/mine'); $('#myOrders').innerHTML = orders.length ? `<div class="table-responsive"><table class="table"><thead><tr><th>訂單編號</th><th>內容</th><th>金額</th><th>狀態</th><th>時間</th></tr></thead><tbody>${orders.map(o => `<tr><td>${o.orderNumber}</td><td>${o.meals.map(m => `${m.name} × ${m.quantity}`).join('<br>')}</td><td>${money(o.totalPrice)}</td><td>${statusText(o.status)}</td><td>${new Date(o.createdAt).toLocaleString('zh-TW')}</td></tr>`).join('')}</tbody></table></div>` : '尚無訂單。'; } catch (e) { $('#myOrders').textContent = e.message; } }
const statusText = s => ({ pending: '待處理', processing: '製作中', completed: '已完成', cancelled: '已取消' }[s] || s);
async function loadAdmin() { if (user()?.role !== 'admin' || !$('#admin') || !$('#period')) return; try { const period = $('#period').value; const data = await request(`/dashboard?period=${period}`); $('#kpis').innerHTML = [['訂單數',data.totals.orderCount],['營收',money(data.totals.revenue)],['已完成',data.totals.completed],['完成率',data.totals.orderCount ? `${Math.round(data.totals.completed/data.totals.orderCount*100)}%` : '0%']].map(([k,v]) => `<div class="col-md-3"><div class="card p-3"><small>${k}</small><strong class="fs-3">${v}</strong></div></div>`).join(''); $('#mealUsage').innerHTML = data.meals.length ? data.meals.map(m => `<div class="d-flex justify-content-between border-bottom py-2"><span>${m.name}</span><b>${m.quantity} 份</b></div>`).join('') : '本期間尚無餐點資料'; if (salesChart) salesChart.destroy(); salesChart = new Chart($('#salesChart'), { type: 'bar', data: { labels: data.sales.map(x => x.label), datasets: [{ label: '營收', data: data.sales.map(x => x.revenue), backgroundColor: '#f05a19' }] }, options: { plugins: { title: { display: true, text: '銷售業績' } }, scales: { y: { beginAtZero: true } } } }); const all = await request('/orders'); $('#adminOrders').innerHTML = all.orders.map(o => `<tr><td>${o.orderNumber}</td><td>${o.customerName}</td><td>${money(o.totalPrice)}</td><td><select class="form-select form-select-sm" onchange="changeStatus(${o.id},this.value)">${['pending','processing','completed','cancelled'].map(s => `<option value="${s}" ${o.status === s ? 'selected' : ''}>${statusText(s)}</option>`).join('')}</select></td><td>${new Date(o.createdAt).toLocaleString('zh-TW')}</td><td><button class="btn btn-sm btn-outline-danger" onclick="deleteOrder(${o.id})">刪除</button></td></tr>`).join(''); } catch (e) { alert(e.message); } }
window.changeStatus = async (id, status) => { try { await request(`/orders/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); loadAdmin(); } catch (e) { alert(e.message); } };
window.deleteOrder = async id => { if (!confirm('確定要刪除此訂單？')) return; try { await request(`/orders/${id}`, { method: 'DELETE' }); loadAdmin(); } catch (e) { alert(e.message); } };
$('#loginForm').onsubmit = async e => { e.preventDefault(); try { const data = Object.fromEntries(new FormData(e.target)); const r = await request('/login', { method: 'POST', body: JSON.stringify(data) }); localStorage.setItem('mars_token', r.token); localStorage.setItem('mars_user', JSON.stringify(r.user)); renderAccount(); loadMine(); loadAdmin(); } catch (e) { alert(e.message); } };
$('#registerForm').onsubmit = async e => { e.preventDefault(); try { const r = await request('/register', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(e.target))) }); localStorage.setItem('mars_token', r.token); localStorage.setItem('mars_user', JSON.stringify(r.user)); renderAccount(); loadMine(); alert('註冊成功，已登入。'); } catch (e) { alert(e.message); } };
$('#orderForm').onsubmit = async e => { e.preventDefault(); if (!token()) return openMemberLogin(); if (!cart.length) return alert('請先加入餐點。'); try { const meals = cart.map(({ label, ...item }) => ({ ...item, name: label || item.name })); const data = { ...Object.fromEntries(new FormData(e.target)), meals, totalPrice: cart.reduce((n,x) => n+x.price*x.quantity,0) }; const r = await request('/orders', { method: 'POST', body: JSON.stringify(data) }); cart=[]; renderCart(); e.target.reset(); alert(`訂單成立：${r.orderNumber}`); loadMine(); if (user()?.role === 'admin') loadAdmin(); } catch (e) { alert(e.message); } };
if ($('#period')) $('#period').onchange = loadAdmin;
if ($('#downloadReport')) $('#downloadReport').onclick = async () => { try { const response = await fetch(`${API}/dashboard/report.csv?period=${$('#period').value}`, { headers: { Authorization: `Bearer ${token()}` } }); if (!response.ok) throw new Error('報表下載失敗'); const link = document.createElement('a'); link.href = URL.createObjectURL(await response.blob()); link.download = `marsburger-${$('#period').value}-report.csv`; link.click(); URL.revokeObjectURL(link.href); } catch (e) { alert(e.message); } };
window.openMemberLogin = () => bootstrap.Modal.getOrCreateInstance(document.querySelector('#memberLoginModal')).show();
document.querySelectorAll('.hero .btn-mars, .hero .btn-cyber').forEach(button => button.addEventListener('click', event => { event.preventDefault(); openMemberLogin(); }));
$('#modalLoginForm').onsubmit = async event => { event.preventDefault(); try { const result = await request('/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); localStorage.setItem('mars_token', result.token); localStorage.setItem('mars_user', JSON.stringify(result.user)); bootstrap.Modal.getInstance(document.querySelector('#memberLoginModal')).hide(); renderAccount(); loadMine(); loadAdmin(); } catch (error) { alert(error.message); } };
$('#goRegister').onclick = () => { bootstrap.Modal.getInstance(document.querySelector('#memberLoginModal')).hide(); document.querySelector('#auth').scrollIntoView({ behavior: 'smooth' }); document.querySelector('#registerForm input[name="username"]').focus(); };
$('#forgotPassword').onclick = () => { window.location.href = 'mailto:xocialphobia@gmail.com?subject=' + encodeURIComponent('MARS Burger｜忘記密碼重設申請') + '&body=' + encodeURIComponent('您好，我想申請重設 MARS Burger 會員密碼。\n\n註冊 Email：\n會員帳號：\n'); };
renderMenu(); renderCart(); renderAccount(); loadMine(); loadAdmin();
